on:
  push:
    branches:
      - master
name: Release
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & Build
        run: |
          npm i
          nx build ngx-fab-menu --prod

      - name: Push To Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/libs/ngx-fab-menu/*"
          token: ${{ secrets.TOKEN }}
